site:
    title: "CaddyLiu Blog"
    subtitle: "生活 技术 产品"
    limit: 10
    theme: theme
    lang: zh
    url: "http://www.inkpaper.io/blog"
    comment: username
    logo: "-/images/avatar.JPG"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "Bigrain"
        intro: "一心向往产品狗"
        avatar: "-/images/avatar.JPG"

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
